all: true
include:
  - lib/**/*.js
  - lib/**/*.ts
exclude:
  - lib/asm-providers/generated/asm-docs-*.js
  - lib/compilers/fake-for-test.js
report-dir: ./out/coverage
reporter:
  - lcov
require:
  - esm
  - source-map-support/register
  - ts-node/register
