name: Compiler Explorer Frontend Testing

on: [push]
jobs:
  cypress-run:
    if: github.repository_owner == 'compiler-explorer'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean
        run: make clean
      - name: Install prerequisites
        run: make prereqs
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
      - name: Cypress run Chrome
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: 'http://localhost:10240'
          config: screenshotOnRunFailure=false,video=false
          browser: chrome
      - name: Cypress run Firefox
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: 'http://localhost:10240'
          config: screenshotOnRunFailure=false,video=false
          browser: firefox
