name: Compiler Explorer Frontend Testing

on: [push]
jobs:
  cypress-run:
    if: github.repository_owner == 'compiler-explorer'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install prerequisites
        run: make prereqs
      - name: Setup browser
        uses: browser-actions/setup-${{ matrix.browser }}@latest
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: 'http://localhost:10240'
          config: screenshotOnRunFailure=false,video=false
          browser: ${{ matrix.browser }}
